import express, { Request, Response } from 'express';
import { v4 as uuidv4 } from 'uuid';
import { IntentParser } from './intent-parser';
import { UnitDisambiguator } from './disambiguation';

const PORT = process.env.PORT || 3002;
const NODE_ENV = process.env.NODE_ENV || 'development';

const app = express();
const intentParser = new IntentParser();
const disambiguator = new UnitDisambiguator();

// Middleware
app.use(express.json());

// Request logging
app.use((req, res, next) => {
  const requestId = uuidv4();
  const startTime = Date.now();

  const originalSend = res.send;
  res.send = function (data: any) {
    const duration = Date.now() - startTime;
    console.log(
      `[${requestId}] ${req.method} ${req.path} - ${res.statusCode} (${duration}ms)`
    );
    return originalSend.call(this, data);
  };

  next();
});

// ============= ENDPOINTS =============

/**
 * POST /api/transcribe
 * Parse a voice transcript into an intent
 */
app.post('/api/transcribe', (req: Request, res: Response) => {
  try {
    const { transcript, matchContext } = req.body;

    if (!transcript) {
      res.status(400).json({ error: 'transcript is required' });
      return;
    }

    // Parse the transcript
    const intent = intentParser.parseIntent(transcript);

    // Enhance intent with context if available
    let confirmationRequired = intent.requiresConfirmation;
    let confirmationPrompt = intent.confirmationPrompt;

    // For move_unit intents with ambiguous unit names, check if disambiguation is needed
    if (
      intent.type === 'move_unit' &&
      matchContext?.activeUnits &&
      intent.entities.unitName
    ) {
      const disambiguationResult = disambiguator.disambiguate(
        intent.entities.unitName,
        matchContext.activeUnits
      );

      if (disambiguationResult.ambiguous) {
        confirmationRequired = true;
        confirmationPrompt = disambiguationResult.prompt;
      } else if (disambiguationResult.matched) {
        // Update entity with matched unit
        intent.entities.unitId = disambiguationResult.matched.id;
      }
    }

    res.json({
      intent: {
        ...intent,
        requiresConfirmation,
        confirmationPrompt,
      },
      confidence: intent.confidence,
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * POST /api/synthesize
 * Generate speech from text (returns SSML and placeholder audio URL)
 */
app.post('/api/synthesize', (req: Request, res: Response) => {
  try {
    const { text, priority = 'normal' } = req.body;

    if (!text) {
      res.status(400).json({ error: 'text is required' });
      return;
    }

    // Escape special characters for SSML
    const escapedText = text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

    // Build SSML based on priority
    let ssml: string;
    switch (priority) {
      case 'urgent':
        ssml = `<speak>
          <prosody rate="1.2" pitch="+10%">
            ${escapedText}
          </prosody>
        </speak>`;
        break;

      case 'error':
        ssml = `<speak>
          <prosody rate="0.9" pitch="-5%">
            <say-as interpret-as="characters">ERROR</say-as>
            ${escapedText}
          </prosody>
        </speak>`;
        break;

      default:
        ssml = `<speak>${escapedText}</speak>`;
    }

    res.json({
      ssml,
      // In production, this would be a real audio URL from a TTS service
      // For MVP, the client uses Web Speech API or client-side TTS
      audioUrl: null,
      priority,
      message:
        'SSML returned for client-side TTS synthesis. Actual audio generated by client.',
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * GET /api/health
 * Health check
 */
app.get('/api/health', (req: Request, res: Response) => {
  res.json({
    status: 'ok',
    service: 'voice-service',
    timestamp: new Date().toISOString(),
    capabilities: [
      'intent_parsing',
      'unit_disambiguation',
      'ssml_generation',
    ],
  });
});

/**
 * POST /api/test-intent
 * Test intent parsing (debugging endpoint)
 */
app.post('/api/test-intent', (req: Request, res: Response) => {
  try {
    const { transcript } = req.body;

    if (!transcript) {
      res.status(400).json({ error: 'transcript is required' });
      return;
    }

    const intent = intentParser.parseIntent(transcript);

    res.json({
      transcript,
      intent,
      explanation: `Parsed as "${intent.type}" with confidence ${(intent.confidence * 100).toFixed(0)}%`,
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ============= ERROR HANDLING =============

app.use((err: any, req: Request, res: Response) => {
  console.error('Unhandled error:', err);
  res.status(500).json({
    error: 'Internal server error',
    message: err.message,
    ...(NODE_ENV === 'development' && { stack: err.stack }),
  });
});

// ============= SERVER START =============

app.listen(PORT, () => {
  console.log(`
╔═══════════════════════════════════════════════════════╗
║   Helm Warhammer 40K Referee - Voice Service          ║
╚═══════════════════════════════════════════════════════╝

🎤 Service:     http://localhost:${PORT}
📋 Health:      http://localhost:${PORT}/api/health

Endpoints:
  POST   http://localhost:${PORT}/api/transcribe
  POST   http://localhost:${PORT}/api/synthesize
  POST   http://localhost:${PORT}/api/test-intent

Intent Types Supported:
  - move_unit
  - declare_attack
  - roll_dice
  - use_stratagem
  - advance_phase
  - score_points
  - query_rule
  - undo
  - select_unit
  - show_targets

Example usage:
  curl -X POST http://localhost:${PORT}/api/test-intent \\
    -H "Content-Type: application/json" \\
    -d '{"transcript": "move Tactical Infantry Alpha"}'

Environment:    ${NODE_ENV}
Press Ctrl+C to stop
  `);
});

export { app, intentParser, disambiguator };
